# Create a program that will play the "cows and bulls" game with the user.
# The game works like this:

#  - Randomly generate a 4-digit number.
#  - Ask the user to guess a 4-digit number.
#  - For every digit that the user guessed correctly in the correct place,
#     they have a "cow".
#  - For every digit the user guessed correctly, but not in the correct
#     place is a "bull."
#  - Every time the user makes a guess, tell them how many "cows" and
#     "bulls" they have.
#  - Once the user guesses the correct number, the game is over.
#  - Keep track of the number of guesses the user makes throughout the game
#     and tell the user at the end.

# An example run could look like this: (the number generated by the computer is 1038)
'''
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ... <user keeps guessing> ...
  >>> 1083
  2 cow, 2 bulls
  >>> 1038
  Congratulations! That is correct!
  It took 14 guesses to get the correct number.
'''
import random

playing = True

answer = list(str(random.randint(1000, 9999)))

guess_attempts = 0

while(playing):
    print(answer)
    user_guess = list(input("Enter a 4 digit number between 1000-9999: "))
    guess_attempts += 1

    #User guesses correct
    if answer == user_guess:
        print("Congratulations! You win!")
        print(f"It took you {guess_attempts} guesses")
        playing = False

    #User quits the game
    elif user_guess == list("quit"):
        print("User has quit")
        print("The answer was: ", str(answer))
        playing = False

    #User inputs a guess that is not 4 characters
    elif len(user_guess) != 4:
        print("Please input a 4 digit number")
        print("LENGTH OF USER'S GUESS: ",(len(user_guess)))

    #User inputs a number that is in the answer
    elif user_guess[0] in answer or user_guess[1] in answer or user_guess[2] or user_guess[3] in answer:
        bull_list = []
        cow_list = []
        copy_list = answer[:]
        new_copy_list = user_guess[:]
        i = 0

        while i < len(copy_list):
            if new_copy_list[i] == copy_list[i]:
                cow_list.append(new_copy_list[i])
                del copy_list[i]
                del new_copy_list[i]
                i -= 1
            i += 1

        i = 0

        while i < len(copy_list):
            if (new_copy_list[i] in copy_list):
                bull_list.append(new_copy_list[i])
            i += 1
            

        print(f"COW: {len(cow_list)}")
        print(f"BULL: {len(bull_list)}")

    #User inputs a number that is not in the answer
    elif user_guess not in answer:
        print(f"COW: 0")
        print(f"BULL: 0")


    
